services:
  - type: web
    name: weathernow-app
    env: node
    plan: free
    buildCommand: npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENWEATHER_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
